name: mandelbrot-background
version: '1.11'
summary: Mandelbrot Background Drawing App
description: |
  Create your own Mandelbrot desktop backgrounds
confinement: strict 
#confinement: devmode 
base: core22
grade: stable
icon: snap/gui/mandelbrot-background.png

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
    - dpkg-dev
    stage-packages:
    - libxkbcommon0
    - shared-mime-info
    - libqt5gui5
    - libgdk-pixbuf2.0-0
    - libqt5svg5 # for loading icon themes which are svg
    - locales-all
    - xdg-user-dirs
    - fcitx-frontend-qt5
#    - libxcb-xinerama0
#    - ttf-ubuntu-font-family
#    - try: [appmenu-qt5] # not available on core18
    #build-packages:
    #  - qtbase5-dev
    #  - dpkg-dev
    #make-parameters:
    #  - FLAVOR=qt5
    #plugin: make
    #source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    #source-subdir: qt
    #stage-packages:
    #  - libxkbcommon0
    #  - ttf-ubuntu-font-family
    #  - dmz-cursor-theme
    #  - light-themes
    #  - adwaita-icon-theme
    #  - gnome-themes-standard
    #  - shared-mime-info
    #  - libqt5gui5
    #  - libgdk-pixbuf2.0-0
    #  - libqt5svg5
#   #   - appmenu-qt5
    #  - locales-all
    #  - xdg-user-dirs

  mainapp:
    after: [desktop-qt5]
    plugin: python
#    python-version: python3
    python-packages:
    - hjson 
    - argparse
    source-type: local 
#    source: [ 'bin', 'display', 'mbg', 'templates', 'zoom', 'mbg.py'] 
    source: . 
#    requirements: requirements.txt
#    qt-version: qt5
    stage-packages:
    - python-six
    - python3-pyqt5
#    - python-json-tricks
   
  templates:
    after: [mainapp]
    plugin: dump 
    source: templates 
    organize: 
      '*': templates/

  zoom:
    after: [mainapp]
    plugin: dump 
    source: zoom 
    organize: 
      '*': zoom/

  display:
    after: [mainapp]
    plugin: dump 
    source: display 
    organize: 
      '*': display/

  colors:
    after: [mainapp]
    plugin: dump 
    source: colors 
    organize: 
      '*': colors/


#  mandelbrot-background:
#    after: [mainapp]
#    plugin: python
#    python-version: python3
#    source-type: local 
#    source: . 
#    organize: [ "mbg.py: mbg.py", "bin/__init__.py" "bin/__init__.py 
#    - bin/bmp.py: bin/__init__.py 

#  hooks:
#    install:
#      command-chain:
#        - snap/command-chain/desktop-launch
#    post-refresh:
#      command-chain:
#        - snap/command-chain/desktop-launch

##  desktop-launch:
#      plugin: make
#      source: desktop-launch
#      build-packages:
#        - rsync
#        - libgail-dev
#        - libgtk-3-dev
#        - libgtk2.0-dev
#      stage-packages:
#        - appmenu-gtk2-module
#        - gtk2-engines
#        - gtk2-engines-pixbuf
#        - libatk-adaptor
#        - libcanberra-gtk-module
#        - libgail-common

apps:
  mandelbrot-background:
    command: bin/desktop-launch mandelbrot-background
#    desktop: snap/gui/mandelbrot-background.desktop
#    command-chain: [snap/command-chain/desktop-launch]
#    command: desktop-launch bin/mandelbrot-background
#    command-chain:
#      - bin/desktop-launch
    environment:
      DISABLE_WAYLAND: 1
    plugs: ['desktop', 'framebuffer', 'camera', 'network', 'home', 'opengl', 'x11','desktop-legacy']
