name: mandelbrot-background
version: '1.0'
summary: Mandelbrot Drawer
description: |
  Create your own Mandelbrot decktop backgrounds
confinement: devmode
base: core18

grade: stable

parts:
  pymandelbrot:
    plugin: python
    python-version: python3
    source: https://github.com/craig-warner/MandelbrotBackground.git
    stage-packages:
    - python-six

apps:
  mandelbrot-background:
    command: bin/mandelbrot-background